const menuItems = [
  // ── STARTERS ─────────────────────────────────────────────
  {
    name: 'Pesarattu',
    category: 'Starters',
    description: 'Crispy green moong dal crepes served with ginger chutney and upma – a traditional Andhra morning favourite.',
    price: 80,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Punugulu',
    category: 'Starters',
    description: 'Golden fried rice-urad batter balls, crunchy outside, soft inside, served with tangy tomato chutney.',
    price: 70,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Chicken 65',
    category: 'Starters',
    description: 'Deep-fried marinated chicken tossed with curry leaves, green chillies and a secret spice blend.',
    price: 220,
    image: '',
    featured: true,
    isAvailable: true,
  },
  {
    name: 'Prawns Fry',
    category: 'Starters',
    description: 'Juicy prawns coated in Andhra masala and pan-fried to perfection with onions and capsicum.',
    price: 280,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Paneer Tikka',
    category: 'Starters',
    description: 'Soft cottage cheese cubes marinated in yogurt and spices, grilled in tandoor until smoky and golden.',
    price: 180,
    image: '',
    featured: false,
    isAvailable: true,
  },

  // ── BIRYANI ──────────────────────────────────────────────
  {
    name: 'Royal Chicken Biryani',
    category: 'Biryani',
    description: 'Dum-cooked basmati rice layered with tender chicken, saffron, fried onions and aromatic whole spices.',
    price: 280,
    image: '',
    featured: true,
    isAvailable: true,
  },
  {
    name: 'Mutton Biryani',
    category: 'Biryani',
    description: 'Slow-cooked succulent mutton pieces with long-grain basmati, rose water and traditional Andhra spices.',
    price: 350,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Prawns Biryani',
    category: 'Biryani',
    description: 'Coastal style biryani with juicy prawns, coconut milk-infused rice and a hint of kewra water.',
    price: 320,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Veg Dum Biryani',
    category: 'Biryani',
    description: 'Aromatic vegetable biryani slow-cooked in dum style with mixed vegetables, mint and golden saffron.',
    price: 200,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Egg Biryani',
    category: 'Biryani',
    description: 'Boiled eggs marinated in masala and layered with fragrant basmati rice for a hearty everyday meal.',
    price: 200,
    image: '',
    featured: false,
    isAvailable: true,
  },

  // ── TANDOORI ─────────────────────────────────────────────
  {
    name: 'Tandoori Chicken',
    category: 'Tandoori',
    description: 'Half chicken marinated overnight in yogurt and hand-ground spices, roasted in a clay tandoor oven.',
    price: 320,
    image: '',
    featured: true,
    isAvailable: true,
  },
  {
    name: 'Chicken Seekh Kebab',
    category: 'Tandoori',
    description: 'Minced chicken blended with green chillies, coriander and spices, skewered and char-grilled in tandoor.',
    price: 260,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Malai Chicken Tikka',
    category: 'Tandoori',
    description: 'Boneless chicken pieces marinated in cream, cashew paste and mild spices, giving a melt-in-mouth texture.',
    price: 280,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Paneer Malai Tikka',
    category: 'Tandoori',
    description: 'Cottage cheese chunks coated in a rich cream and cheese marinade, cooked to a beautiful golden hue.',
    price: 240,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Fish Tikka',
    category: 'Tandoori',
    description: 'Boneless fish fillets marinated in Andhra-spiced yogurt, skewered and flame-grilled to perfection.',
    price: 300,
    image: '',
    featured: false,
    isAvailable: true,
  },

  // ── DESSERTS ─────────────────────────────────────────────
  {
    name: 'Double Ka Meetha',
    category: 'Desserts',
    description: 'Hyderabadi bread pudding soaked in thickened milk, garnished with nuts and saffron—a royal indulgence.',
    price: 120,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Gulab Jamun (4 pcs)',
    category: 'Desserts',
    description: 'Soft khoya dumplings fried golden and soaked in rose-cardamom sugar syrup, served warm.',
    price: 100,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Qubani Ka Meetha',
    category: 'Desserts',
    description: 'A classic Hyderabadi dessert made with dried apricots, sugar syrup and topped with fresh cream.',
    price: 130,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Rabri Phirni',
    category: 'Desserts',
    description: 'Creamy rice pudding topped with thick rabri, pistachios and silver leaf—served chilled in earthen bowls.',
    price: 110,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Ice Cream (2 scoops)',
    category: 'Desserts',
    description: 'Premium scoops of vanilla, mango or rose ice cream topped with dry fruits and rose petals.',
    price: 90,
    image: '',
    featured: false,
    isAvailable: true,
  },

  // ── DRINKS ───────────────────────────────────────────────
  {
    name: 'Mango Lassi',
    category: 'Drinks',
    description: 'Thick, chilled yogurt blended with Alphonso mango pulp, a pinch of cardamom and sugar.',
    price: 80,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Masala Chai',
    category: 'Drinks',
    description: 'Aromatic Indian spiced tea brewed with ginger, cardamom, cinnamon and tulsi leaves.',
    price: 40,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Fresh Lime Soda',
    category: 'Drinks',
    description: 'Chilled soda with freshly squeezed lime, black salt and mint leaves – sweet or salty.',
    price: 60,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Rose Sharbat',
    category: 'Drinks',
    description: 'Refreshing chilled drink made with natural rose syrup, sabja seeds and cold milk.',
    price: 70,
    image: '',
    featured: false,
    isAvailable: true,
  },
  {
    name: 'Filter Coffee',
    category: 'Drinks',
    description: 'South Indian filter coffee brewed with freshly ground Coorg beans, served in traditional steel tumbler.',
    price: 50,
    image: '',
    featured: false,
    isAvailable: true,
  },
];

module.exports = menuItems;
